"""Canonical pipeline package for routing, runtime, recovery, hooks, and budgets."""

import subprocess
import time

from litehive.agents import SubagentManager
from litehive.pipeline.states import PipelineState, _ROUTES, _STEPS_FROM
from litehive.pipeline.core import (
    RunResult,
    StageExecutor,
    TaskExecutionRunner,
    _human_checkpoint_reason,
    _reason_code_for_report,
)
from litehive.pipeline._types import (
    DirtyWorktreeFinding,
    DirtyWorktreeGateReport,
    EngineBudgetLedger,
    ExecutionSummary,
    ResolvedExecutionRetryPolicy,
    RollbackSummary,
    SingleTaskRunSummary,
    TaskPoolRunSummary,
    TaskPoolStopConditions,
    _path_within,
)
from litehive.pipeline._budget import (
    _budget_ledger_from_conditions,
    _budget_ledger_from_config,
    _count_execution_limits,
    _engine_attempt_order,
    _execution_exhausted_limit_fallbacks,
    _execution_hit_limit,
    _execution_limit_kind,
    _limit_stop_condition_is_configured,
)
from litehive.pipeline._models import (
    _execution_retry_model_family,
    _is_recovery_run,
    _resolve_stage_retry_limit,
    _retry_backoff_seconds,
    _role_for_step,
    _set_continuation_handoff,
    active_engine_freezes,
    is_engine_frozen,
    resolve_engine_attempt_order,
    resolve_engine_name,
    resolve_engine_plan,
    resolve_execution_retry_policy,
    resolve_model,
    resolve_task_retry_policy,
    workspace_model_for_engine,
)
from litehive.pipeline._recovery import (
    _attempt_commit_recovery,
    _attempt_stage_recovery,
    _capture_persisted_files,
    _classify_recovery_failure_owner,
    _require_completed_task,
    _resolve_recovery_engine,
    _restore_persisted_files,
    _traceback_fingerprint,
    _traceback_frame_paths,
    _traceback_text,
    recover_completed_task,
    rollback_completed_task,
)
from litehive.pipeline._commit import _commit_to_git_report
from litehive.pipeline._builder import build_executor
from litehive.pipeline._hooks import (
    _attach_runner_hook_results,
    _execute_runner_hook,
    _flatten_runner_hook_feedback,
    _flatten_runner_hook_warnings,
    _run_runner_hooks_for_stage,
    _runner_hook_feedback,
    _runner_hook_point,
    _runner_hook_warnings,
)
from litehive.pipeline._orchestration import (
    drain_task_pool,
    resolve_next_task,
    run_next_task,
    run_next_task_with_override,
    run_single_task,
    run_task,
)
from litehive.pipeline._pool_control import (
    _finalize_pool_run,
    _human_checkpoint_stop_reason,
    _pool_stop_reason,
    _requires_continue_or_rollback,
    _single_task_pre_stop_reason,
    _single_task_stop_reason,
)
from litehive.pipeline._parallel import (
    IntegrationResult,
    ParallelRunSummary,
    _clear_parallel_active_tasks,
    _integrate_completed_task,
    _run_single_parallel_task,
    _select_parallel_tasks,
    run_parallel_tasks,
)
from litehive.pipeline._worktree import (
    _allowed_commit_paths,
    _dirty_entry_paths,
    _dirty_worktree_owner_task,
    _git_worktree_blocks_pool,
    _git_worktree_is_dirty,
    _resolve_task_execution_root,
    _task_can_resume_with_owned_dirty_paths,
    _task_worktree_path,
    _unexpected_dirty_paths,
    inspect_dirty_worktree_gate,
)

__all__ = [
    "PipelineState",
    "_ROUTES",
    "_STEPS_FROM",
    "RunResult",
    "StageExecutor",
    "TaskExecutionRunner",
    "_human_checkpoint_reason",
    "_reason_code_for_report",
    "subprocess",
    "time",
    "SubagentManager",
    "DirtyWorktreeFinding",
    "DirtyWorktreeGateReport",
    "EngineBudgetLedger",
    "ExecutionSummary",
    "ResolvedExecutionRetryPolicy",
    "RollbackSummary",
    "SingleTaskRunSummary",
    "TaskPoolRunSummary",
    "TaskPoolStopConditions",
    "_path_within",
    "_budget_ledger_from_conditions",
    "_budget_ledger_from_config",
    "_count_execution_limits",
    "_engine_attempt_order",
    "_execution_exhausted_limit_fallbacks",
    "_execution_hit_limit",
    "_execution_limit_kind",
    "_limit_stop_condition_is_configured",
    "_execution_retry_model_family",
    "_is_recovery_run",
    "_resolve_stage_retry_limit",
    "_retry_backoff_seconds",
    "_role_for_step",
    "_set_continuation_handoff",
    "active_engine_freezes",
    "is_engine_frozen",
    "resolve_engine_attempt_order",
    "resolve_engine_name",
    "resolve_execution_retry_policy",
    "resolve_engine_plan",
    "resolve_model",
    "resolve_task_retry_policy",
    "workspace_model_for_engine",
    "_attempt_commit_recovery",
    "_attempt_stage_recovery",
    "_capture_persisted_files",
    "_classify_recovery_failure_owner",
    "_require_completed_task",
    "_resolve_recovery_engine",
    "_restore_persisted_files",
    "_traceback_fingerprint",
    "_traceback_frame_paths",
    "_traceback_text",
    "recover_completed_task",
    "rollback_completed_task",
    "_commit_to_git_report",
    "build_executor",
    "_attach_runner_hook_results",
    "_execute_runner_hook",
    "_flatten_runner_hook_feedback",
    "_flatten_runner_hook_warnings",
    "_run_runner_hooks_for_stage",
    "_runner_hook_feedback",
    "_runner_hook_point",
    "_runner_hook_warnings",
    "drain_task_pool",
    "inspect_dirty_worktree_gate",
    "resolve_next_task",
    "run_next_task",
    "run_next_task_with_override",
    "run_single_task",
    "run_task",
    "_finalize_pool_run",
    "_human_checkpoint_stop_reason",
    "_pool_stop_reason",
    "_requires_continue_or_rollback",
    "_single_task_pre_stop_reason",
    "_single_task_stop_reason",
    "IntegrationResult",
    "ParallelRunSummary",
    "_clear_parallel_active_tasks",
    "_integrate_completed_task",
    "_run_single_parallel_task",
    "_select_parallel_tasks",
    "run_parallel_tasks",
    "_allowed_commit_paths",
    "_dirty_entry_paths",
    "_dirty_worktree_owner_task",
    "_git_worktree_blocks_pool",
    "_git_worktree_is_dirty",
    "_resolve_task_execution_root",
    "_task_can_resume_with_owned_dirty_paths",
    "_task_worktree_path",
    "_unexpected_dirty_paths",
]
